"""Abstracciones propias para agentes especializados."""

from agents.base import (
    AgentContext,
    AgentExecutionError,
    AgentInput,
    BaseAgent,
    StubAgent,
)
from agents.explorer import ExplorerAgent, ExplorerReport, build_explorer_registry
from agents.context_manager import ContextManager, StateContextManager
from agents.implementer import (
    ImplementerAgent,
    ImplementerBlockedError,
    ImplementerResult,
    ScopedWritePolicy,
    WritePolicy,
)
from agents.orchestrator import (
    LLMPlanGenerator,
    LLMTaskAnalyzer,
    MainAgent,
    OrchestrationResult,
    PlanGenerator,
    ResultPresenter,
    TaskAnalysis,
    TaskAnalyzer,
    TextResultPresenter,
)
from agents.project_memory import (
    MemoryCorruptionError,
    ProjectMemory,
    ProjectMemoryError,
)
from agents.repository_detection import (
    BuildSystemDetector,
    LanguageDetector,
    RepositoryDetector,
    TechnologyDetector,
)
from agents.researcher import (
    EvidenceFragment,
    EvidenceSufficiencyEvaluator,
    KnowledgeRetriever,
    ProjectMemoryProvider,
    ResearcherAgent,
    ResearcherResult,
    WebSearchProvider,
)
from agents.tester import (
    StaticCommandProvider,
    SubprocessValidationExecutor,
    TaskStateCommandProvider,
    TesterAgent,
    TesterLimits,
    TesterResult,
    ValidationCommand,
    ValidationCommandProvider,
    ValidationExecutor,
    ValidationSafetyPolicy,
)
from agents.reviewer import (
    DiffProvider,
    DiffSnapshot,
    GitDiffProvider,
    ReviewIssue,
    ReviewerAgent,
    ReviewerResult,
)

__all__ = [
    "AgentContext",
    "AgentExecutionError",
    "AgentInput",
    "BaseAgent",
    "BuildSystemDetector",
    "ContextManager",
    "DiffProvider",
    "DiffSnapshot",
    "ExplorerAgent",
    "ExplorerReport",
    "EvidenceFragment",
    "EvidenceSufficiencyEvaluator",
    "KnowledgeRetriever",
    "GitDiffProvider",
    "ImplementerAgent",
    "ImplementerBlockedError",
    "ImplementerResult",
    "LanguageDetector",
    "LLMPlanGenerator",
    "LLMTaskAnalyzer",
    "MainAgent",
    "MemoryCorruptionError",
    "OrchestrationResult",
    "PlanGenerator",
    "ResultPresenter",
    "RepositoryDetector",
    "ProjectMemoryProvider",
    "ProjectMemory",
    "ProjectMemoryError",
    "ResearcherAgent",
    "ResearcherResult",
    "ReviewIssue",
    "ReviewerAgent",
    "ReviewerResult",
    "StubAgent",
    "StateContextManager",
    "StaticCommandProvider",
    "SubprocessValidationExecutor",
    "TaskStateCommandProvider",
    "ScopedWritePolicy",
    "TechnologyDetector",
    "TaskAnalysis",
    "TaskAnalyzer",
    "TextResultPresenter",
    "TesterAgent",
    "TesterLimits",
    "TesterResult",
    "ValidationCommand",
    "ValidationCommandProvider",
    "ValidationExecutor",
    "ValidationSafetyPolicy",
    "WebSearchProvider",
    "WritePolicy",
    "build_explorer_registry",
]
